// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"

	"github.com/lib/pq"
	uuid "github.com/satori/go.uuid"
)

// Specialist represents a row from 'public.specialist'.
var (
	SpecialistFields  = ` id, name, surname, specialities `
	SpecialistColumns = []string{"id", "name", "surname", "specialities"}
)

type Specialist struct {
	ID           uuid.UUID        `json:"id,omitempty"`           // id
	Name         string           `json:"name,omitempty"`         // name
	Surname      string           `json:"surname,omitempty"`      // surname
	Specialities []Specialityenum `json:"specialities,omitempty"` // specialities

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Specialist exists in the database.
func (s *Specialist) Exists() bool {
	return s._exists
}

// Only for tests usage!
func (s *Specialist) TestOnly_SetExists() {
	s._exists = true
}

// Only for tests usage!
func (s *Specialist) TestOnly_SetDeleted() {
	s._deleted = true
}

// Deleted provides information if the Specialist has been deleted from the database.
func (s *Specialist) Deleted() bool {
	return s._deleted
}

// Insert inserts the Specialist to the database.
func (s *Specialist) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if s._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO public.specialist (` +
		`id, name, surname, specialities` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) RETURNING id`

	// run query
	XOLog(sqlstr, s.ID, s.Name, s.Surname, pq.Array(s.Specialities))
	err = db.QueryRow(sqlstr, s.ID, s.Name, s.Surname, pq.Array(s.Specialities)).Scan(&s.ID)
	if err != nil {
		return err
	}

	// set existence
	s._exists = true

	return nil
}

// Update updates the Specialist in the database.
func (s *Specialist) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !s._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if s._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.specialist SET (` +
		`name, surname, specialities` +
		`) = ( ` +
		`$1, $2, $3` +
		`) WHERE id = $4`

	// run query
	XOLog(sqlstr, s.Name, s.Surname, pq.Array(s.Specialities), s.ID)
	_, err = db.Exec(sqlstr, s.Name, s.Surname, pq.Array(s.Specialities), s.ID)
	return err
}

// Save saves the Specialist to the database.
func (s *Specialist) Save(db XODB) error {
	if s.Exists() {
		return s.Update(db)
	}

	return s.Insert(db)
}

// Upsert performs an upsert for Specialist.
//
// NOTE: PostgreSQL 9.5+ only
func (s *Specialist) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if s._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.specialist (` +
		`id, name, surname, specialities` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`id, name, surname, specialities` +
		`) = (` +
		`EXCLUDED.id, EXCLUDED.name, EXCLUDED.surname, EXCLUDED.specialities` +
		`)`

	// run query
	XOLog(sqlstr, s.ID, s.Name, s.Surname, pq.Array(s.Specialities))
	_, err = db.Exec(sqlstr, s.ID, s.Name, s.Surname, pq.Array(s.Specialities))
	if err != nil {
		return err
	}

	// set existence
	s._exists = true

	return nil
}

// Delete deletes the Specialist from the database.
func (s *Specialist) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !s._exists {
		return nil
	}

	// if deleted, bail
	if s._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.specialist WHERE id = $1`

	// run query
	XOLog(sqlstr, s.ID)
	_, err = db.Exec(sqlstr, s.ID)
	if err != nil {
		return err
	}

	// set deleted
	s._deleted = true

	return nil
}

// SpecialistByID retrieves a row from 'public.specialist' as a Specialist.
//
// Generated from index 'specialist_pkey'.
func SpecialistByID(db XODB, id uuid.UUID) (*Specialist, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, name, surname, specialities ` +
		`FROM public.specialist ` +
		`WHERE id = $1`

	// run query
	XOLog(sqlstr, id)
	s := Specialist{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&s.ID, &s.Name, &s.Surname, pq.Array(&s.Specialities))
	if err != nil {
		return nil, err
	}

	return &s, nil
}
