version: "3.3"
services:
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_logs_debug_level: DEBUG
  postgres:
    restart: always
    build:
       context: backend/migration
       dockerfile: Dockerfile
  backend:
    container_name: backend
    build:
      context: ../src/backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    environment:
      API_PUBLIC_KEY: fb71068ebf8203243a86c64e951f7778
      API_PRIVATE_KEY: 3450a83ffd0cf668ded207e42f46830b
      DB_HOST: postgres
      DB_PORT: 5432
      DB_ADDR:$DB_HOST: $DB_PORT
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: clinicdb
      DB_NAME: clinicdb
      NEO_PATH: 0.0.0.0
    depends_on:
      - postgres
      - neo4j
  frontend:
    container_name: frontend
    build:
      context: ../src/front2
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - backend