package clinic

// Code generated by rest_rpc. DO NOT EDIT.

import (
	"e-clinic/src/tools/http/http_client"
	"e-clinic/src/tools/http/http_server"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-chi/chi"
	uuid "github.com/satori/go.uuid"
	"github.com/sirupsen/logrus"
)

const SpecjalistAssistantRoutePattern = "/api/v1/SpecjalistAssistant"

func RegisterSpecjalistAssistant(instance SpecjalistAssistant, r *chi.Mux, log logrus.FieldLogger) {
	r.Route("/api/v1/SpecjalistAssistant", func(r chi.Router) {
		r.Post("/GetFreeTime", func(writer http.ResponseWriter, request *http.Request) {
			// Reading argument id
			idStr := request.URL.Query().Get("id")
			id, err := uuid.FromString(idStr)
			if err != nil {
				log.WithError(err).Error("can't parse uuid")
				writer.WriteHeader(http.StatusBadRequest)
				return
			}
			// Reading argument timeRange
			rawBody, err := ioutil.ReadAll(request.Body)
			if err != nil {
				log.WithError(err).Error("can't read body")
				writer.WriteHeader(http.StatusBadRequest)
				return
			}
			var timeRange *TimeRange
			if len(rawBody) != 0 {
				timeRange = &TimeRange{}
				if err := json.Unmarshal(rawBody, timeRange); err != nil {
					log.WithError(err).Error("can't unmarshal body")
					writer.WriteHeader(http.StatusBadRequest)
					return
				}
			}

			// Calling function GetFreeTime
			{
				response, responseCode, err := instance.GetFreeTime(id, timeRange)
				writer.WriteHeader(responseCode)
				if err != nil {
					if err := json.NewEncoder(writer).Encode(&struct{ Error string }{Error: err.Error()}); err != nil {
						fmt.Fprintf(writer, "{\"Error\": \"Could not marshal response error\"}")
						log.WithError(err).Error("Could not marshal response error")
					}
					return
				}
				if response != nil {
					if err := json.NewEncoder(writer).Encode(response); err != nil {
						log.WithError(err).Error("Could not write response")
						writer.WriteHeader(http.StatusInternalServerError)
						if err := json.NewEncoder(writer).Encode(&struct{ Error string }{Error: err.Error()}); err != nil {
							fmt.Fprintf(writer, "{\"Error\": \"Could not marshal response error\"}")
							log.WithError(err).Error("Could not marshal response error")
						}
						return
					}
				}
			}
		})
		r.Get("/isUp", func(writer http.ResponseWriter, request *http.Request) {
			writer.WriteHeader(http.StatusOK)
		})
	})
}

type SpecjalistAssistantRestClient struct {
	address string
	client  http_client.DefaultHTTPClient
	errs    []error
}

func NewSpecjalistAssistantRestClient(address string, client http_client.DefaultHTTPClient) (*SpecjalistAssistantRestClient, error) {
	packageErrors := []error{}

	restClient := &SpecjalistAssistantRestClient{
		address: address,
		client:  client,
		errs:    packageErrors,
	}

	// restClient is returned to avoid panics, some services may work without working rest client
	if code := restClient.isUp(); code != http.StatusOK {
		return restClient, http_server.ServerNotUp
	}
	return restClient, nil
}

func NewSpecjalistAssistantRestClientErrWrap(address string, client http_client.DefaultHTTPClient, log logrus.FieldLogger) *SpecjalistAssistantRestClient {
	restClient, err := NewSpecjalistAssistantRestClient(address, client)
	if err != nil {
		log.WithError(err).Warn("failed to create SpecjalistAssistantRestClient")
	}
	return restClient
}

func (serviceInstance *SpecjalistAssistantRestClient) wrapError(errMsg interface{}) error {
	for _, er := range serviceInstance.errs {
		if strings.EqualFold(errMsg.(string), er.Error()) {
			return er
		}
	}
	return fmt.Errorf("%v", errMsg)
}

func (serviceInstance *SpecjalistAssistantRestClient) GetFreeTime(id uuid.UUID, timeRange *TimeRange) (*TimeRanges, int, error) {
	u, err := url.Parse(serviceInstance.address + "/api/v1/SpecjalistAssistant/GetFreeTime")
	if err != nil {
		return nil, -1, err
	}
	query := u.Query()
	query.Set("id", id.String())

	u.RawQuery = query.Encode()

	data, err := json.Marshal(timeRange)
	if err != nil {
		return nil, -1, err
	}
	resp := serviceInstance.client.Post(u.String(), data)
	if resp.Err != nil {
		return nil, -1, resp.Err
	}

	if len(resp.Body) > 0 {
		respErr := map[string]interface{}{}
		if err := json.Unmarshal(resp.Body, &respErr); err != nil {
			return nil, resp.StatusCode, err
		}
		if errorMessage, found := respErr["Error"]; found && len(respErr) == 1 {
			return nil, resp.StatusCode, serviceInstance.wrapError(errorMessage)
		}
	}
	respJson := &TimeRanges{}
	if len(resp.Body) > 0 {
		if err := json.Unmarshal(resp.Body, respJson); err != nil {
			return nil, resp.StatusCode, err
		}
	}
	return respJson, resp.StatusCode, nil
}

func (serviceInstance *SpecjalistAssistantRestClient) isUp() int {
	u, err := url.Parse(serviceInstance.address + "/api/v1/SpecjalistAssistant/isUp")
	if err != nil {
		return -1
	}

	resp := serviceInstance.client.Get(u.String())
	if resp.Err != nil {
		return -1
	}

	return resp.StatusCode
}

const PatientAssistantRoutePattern = "/api/v1/PatientAssistant"

func RegisterPatientAssistant(instance PatientAssistant, r *chi.Mux, log logrus.FieldLogger) {
	r.Route("/api/v1/PatientAssistant", func(r chi.Router) {
		r.Post("/CreateAppointment", func(writer http.ResponseWriter, request *http.Request) {
			// Reading argument a
			rawBody, err := ioutil.ReadAll(request.Body)
			if err != nil {
				log.WithError(err).Error("can't read body")
				writer.WriteHeader(http.StatusBadRequest)
				return
			}
			var a *Appointment
			if len(rawBody) != 0 {
				a = &Appointment{}
				if err := json.Unmarshal(rawBody, a); err != nil {
					log.WithError(err).Error("can't unmarshal body")
					writer.WriteHeader(http.StatusBadRequest)
					return
				}
			}

			// Calling function CreateAppointment
			{
				responseCode, err := instance.CreateAppointment(a)
				writer.WriteHeader(responseCode)
				if err != nil {
					if err := json.NewEncoder(writer).Encode(&struct{ Error string }{Error: err.Error()}); err != nil {
						fmt.Fprintf(writer, "{\"Error\": \"Could not marshal response error\"}")
						log.WithError(err).Error("Could not marshal response error")
					}
					return
				}
			}
		})
		r.Post("/GetAppointments", func(writer http.ResponseWriter, request *http.Request) {
			// Reading argument t
			rawBody, err := ioutil.ReadAll(request.Body)
			if err != nil {
				log.WithError(err).Error("can't read body")
				writer.WriteHeader(http.StatusBadRequest)
				return
			}
			var t *TimeRange
			if len(rawBody) != 0 {
				t = &TimeRange{}
				if err := json.Unmarshal(rawBody, t); err != nil {
					log.WithError(err).Error("can't unmarshal body")
					writer.WriteHeader(http.StatusBadRequest)
					return
				}
			}

			// Calling function GetAppointments
			{
				response, responseCode, err := instance.GetAppointments(t)
				writer.WriteHeader(responseCode)
				if err != nil {
					if err := json.NewEncoder(writer).Encode(&struct{ Error string }{Error: err.Error()}); err != nil {
						fmt.Fprintf(writer, "{\"Error\": \"Could not marshal response error\"}")
						log.WithError(err).Error("Could not marshal response error")
					}
					return
				}
				if response != nil {
					if err := json.NewEncoder(writer).Encode(response); err != nil {
						log.WithError(err).Error("Could not write response")
						writer.WriteHeader(http.StatusInternalServerError)
						if err := json.NewEncoder(writer).Encode(&struct{ Error string }{Error: err.Error()}); err != nil {
							fmt.Fprintf(writer, "{\"Error\": \"Could not marshal response error\"}")
							log.WithError(err).Error("Could not marshal response error")
						}
						return
					}
				}
			}
		})
		r.Get("/isUp", func(writer http.ResponseWriter, request *http.Request) {
			writer.WriteHeader(http.StatusOK)
		})
	})
}

type PatientAssistantRestClient struct {
	address string
	client  http_client.DefaultHTTPClient
	errs    []error
}

func NewPatientAssistantRestClient(address string, client http_client.DefaultHTTPClient) (*PatientAssistantRestClient, error) {
	packageErrors := []error{}

	restClient := &PatientAssistantRestClient{
		address: address,
		client:  client,
		errs:    packageErrors,
	}

	// restClient is returned to avoid panics, some services may work without working rest client
	if code := restClient.isUp(); code != http.StatusOK {
		return restClient, http_server.ServerNotUp
	}
	return restClient, nil
}

func NewPatientAssistantRestClientErrWrap(address string, client http_client.DefaultHTTPClient, log logrus.FieldLogger) *PatientAssistantRestClient {
	restClient, err := NewPatientAssistantRestClient(address, client)
	if err != nil {
		log.WithError(err).Warn("failed to create PatientAssistantRestClient")
	}
	return restClient
}

func (serviceInstance *PatientAssistantRestClient) wrapError(errMsg interface{}) error {
	for _, er := range serviceInstance.errs {
		if strings.EqualFold(errMsg.(string), er.Error()) {
			return er
		}
	}
	return fmt.Errorf("%v", errMsg)
}

func (serviceInstance *PatientAssistantRestClient) CreateAppointment(a *Appointment) (int, error) {
	u, err := url.Parse(serviceInstance.address + "/api/v1/PatientAssistant/CreateAppointment")
	if err != nil {
		return -1, err
	}

	data, err := json.Marshal(a)
	if err != nil {
		return -1, err
	}
	resp := serviceInstance.client.Post(u.String(), data)
	if resp.Err != nil {
		return -1, resp.Err
	}

	if len(resp.Body) > 0 {
		respErr := map[string]interface{}{}
		if err := json.Unmarshal(resp.Body, &respErr); err != nil {
			return resp.StatusCode, err
		}
		if errorMessage, found := respErr["Error"]; found && len(respErr) == 1 {
			return resp.StatusCode, serviceInstance.wrapError(errorMessage)
		}
	}
	return resp.StatusCode, nil
}

func (serviceInstance *PatientAssistantRestClient) GetAppointments(t *TimeRange) (*AppointmentList, int, error) {
	u, err := url.Parse(serviceInstance.address + "/api/v1/PatientAssistant/GetAppointments")
	if err != nil {
		return nil, -1, err
	}

	data, err := json.Marshal(t)
	if err != nil {
		return nil, -1, err
	}
	resp := serviceInstance.client.Post(u.String(), data)
	if resp.Err != nil {
		return nil, -1, resp.Err
	}

	if len(resp.Body) > 0 {
		respErr := map[string]interface{}{}
		if err := json.Unmarshal(resp.Body, &respErr); err != nil {
			return nil, resp.StatusCode, err
		}
		if errorMessage, found := respErr["Error"]; found && len(respErr) == 1 {
			return nil, resp.StatusCode, serviceInstance.wrapError(errorMessage)
		}
	}
	respJson := &AppointmentList{}
	if len(resp.Body) > 0 {
		if err := json.Unmarshal(resp.Body, respJson); err != nil {
			return nil, resp.StatusCode, err
		}
	}
	return respJson, resp.StatusCode, nil
}

func (serviceInstance *PatientAssistantRestClient) isUp() int {
	u, err := url.Parse(serviceInstance.address + "/api/v1/PatientAssistant/isUp")
	if err != nil {
		return -1
	}

	resp := serviceInstance.client.Get(u.String())
	if resp.Err != nil {
		return -1
	}

	return resp.StatusCode
}
